# Generated by Django 2.2.6 on 2020-05-19 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('serial_num', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('spec_check', models.BooleanField()),
                ('date_made', models.DateField(blank=True, null=True)),
                ('date_delivered', models.DateField(blank=True, null=True)),
                ('doc_delivered', models.FilePathField(blank=True, path='/home/ankeru/Рабочий стол/Проекты/DBU/media/doc/')),
                ('doc_delivered_original', models.CharField(blank=True, max_length=200)),
                ('label', models.FilePathField(blank=True, path='/home/ankeru/Рабочий стол/Проекты/DBU/media/labels/')),
                ('label_original', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Entity_type',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('img_link', models.ImageField(blank=True, upload_to='images/')),
                ('soft_link', models.CharField(blank=True, max_length=200)),
                ('additional_info', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_num', models.BigIntegerField()),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('date_return', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=200)),
                ('comment', models.CharField(blank=True, max_length=400, null=True)),
                ('admin_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('admin_taken', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('serial_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Entity')),
                ('user_taken', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Entity_type'),
        ),
    ]
