# Generated by Django 2.2.6 on 2020-04-24 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity_type',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('img_link', models.FilePathField(path=mainapp.models.images_path)),
                ('soft_link', models.CharField(max_length=200)),
                ('additional_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('serial_num', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('spec_check', models.BooleanField()),
                ('date_made', models.DateField()),
                ('date_delivered', models.DateField()),
                ('doc_delivered', models.CharField(max_length=200)),
                ('label', models.FilePathField(path=mainapp.models.label_path)),
                ('label_original', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=400)),
                ('entity_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Entity_type')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.Entity', unique=True)),
                ('serial_num', models.CharField(max_length=200)),
                ('date_taken', models.DateField()),
                ('date_return', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=400)),
                ('admin_return', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('admin_taken', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_taken', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
