# Generated by Django 2.2.14 on 2020-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='doc_delivered',
            field=models.FilePathField(blank=True, path='/home/vafedorchenko/DBU-dev_back/media/doc/'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='label',
            field=models.FilePathField(blank=True, path='/home/vafedorchenko/DBU-dev_back/media/labels/'),
        ),
    ]
