# Generated by Django 2.2.14 on 2020-07-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200714_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='entity_name',
            new_name='entity_type_name',
        ),
    ]
