# Generated by Django 2.2.14 on 2020-07-22 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200722_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='entity_type_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Entity_type'),
            preserve_default=False,
        ),
    ]
