# Generated by Django 2.2.6 on 2020-04-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200428_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
