# Generated by Django 2.2.6 on 2020-04-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200428_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='date_delivered',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date_made',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_return',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_taken',
            field=models.DateField(null=True),
        ),
    ]
