# Generated by Django 2.2.14 on 2020-07-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_history_entity_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='entity_type_name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='serial_num',
        ),
        migrations.AddField(
            model_name='history',
            name='Entity_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
