# Generated by Django 2.2.6 on 2020-04-28 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200428_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='admin_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='comment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
