# Generated by Django 2.2.6 on 2020-05-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200428_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity_type',
            name='img_link',
            field=models.ImageField(upload_to='images'),
        ),
    ]
