# Generated by Django 2.2.14 on 2020-07-22 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_history_serial_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='serial_num',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Entity'),
            preserve_default=False,
        ),
    ]
