# Generated by Django 2.2.6 on 2020-05-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200507_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='serial_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Entity'),
        ),
    ]
