# Generated by Django 2.2.14 on 2020-08-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_history_serial_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='Entity_id',
            new_name='entity_id',
        ),
    ]
