# Generated by Django 2.2.6 on 2020-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200507_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='label',
            field=models.FilePathField(path='documents/labels'),
        ),
    ]
