# Generated by Django 2.2.6 on 2020-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200507_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='label',
            field=models.FilePathField(path='labels/'),
        ),
    ]
