# Generated by Django 2.2.6 on 2020-05-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20200507_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='label',
            field=models.FilePathField(path='/home/ankeru/Рабочий стол/Проекты/DBU/media/labels/'),
        ),
    ]
