# Generated by Django 2.2.6 on 2020-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200507_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='doc_delivered_original',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='doc_delivered',
            field=models.FilePathField(path='/home/ankeru/Рабочий стол/Проекты/DBU/media/labels/'),
        ),
    ]
