# Generated by Django 2.2.6 on 2020-05-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20200508_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
    ]
