# Generated by Django 2.2.6 on 2020-05-13 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200513_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='date_delivered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='date_made',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='doc_delivered',
            field=models.FilePathField(blank=True, path='/home/ankeru/Рабочий стол/Проекты/DBU/media/labels/'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='doc_delivered_original',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entity',
            name='label',
            field=models.FilePathField(blank=True, path='/home/ankeru/Рабочий стол/Проекты/DBU/media/labels/'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='label_original',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entity',
            name='note',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='entity_type',
            name='additional_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entity_type',
            name='img_link',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='entity_type',
            name='soft_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='history',
            name='admin_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='admin_taken',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_return',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_taken',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='history',
            name='user_taken',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
