# Generated by Django 2.2.6 on 2020-05-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200515_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='doc_delivered',
            field=models.FilePathField(blank=True, path='/home/ankeru/Рабочий стол/Проекты/DBU/media/doc/'),
        ),
    ]
